package net.flamgop.vulkanic.memory.image;

import org.lwjgl.vulkan.*;

public enum VulkanicImageLayout {
    UNDEFINED(VK10.VK_IMAGE_LAYOUT_UNDEFINED),
    GENERAL(VK10.VK_IMAGE_LAYOUT_GENERAL),
    COLOR_ATTACHMENT_OPTIMAL(VK10.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
    DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK10.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
    DEPTH_STENCIL_READ_ONLY_OPTIMAL(VK10.VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL),
    SHADER_READ_ONLY_OPTIMAL(VK10.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
    TRANSFER_SRC_OPTIMAL(VK10.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
    TRANSFER_DST_OPTIMAL(VK10.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
    PREINITIALIZED(VK10.VK_IMAGE_LAYOUT_PREINITIALIZED),
    DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL(VK11.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL),
    DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL(VK11.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL),
    DEPTH_ATTACHMENT_OPTIMAL(VK12.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL),
    DEPTH_READ_ONLY_OPTIMAL(VK12.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL),
    STENCIL_ATTACHMENT_OPTIMAL(VK12.VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL),
    STENCIL_READ_ONLY_OPTIMAL(VK12.VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL),
    READ_ONLY_OPTIMAL(VK13.VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL),
    ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL),
    RENDERING_LOCAL_READ(VK14.VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ),
    PRESENT_SRC_KHR(KHRSwapchain.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR),
    VIDEO_DECODE_DST_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR),
    VIDEO_DECODE_SRC_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR),
    VIDEO_DECODE_DPB_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR),
    SHARED_PRESENT_KHR(KHRSharedPresentableImage.VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR),
    FRAGMENT_DENSITY_MAP_OPTIMAL_EXT(EXTFragmentDensityMap.VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT),
    FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR(KHRFragmentShadingRate.VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR),
    VIDEO_ENCODE_DST_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR),
    VIDEO_ENCODE_SRC_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR),
    VIDEO_ENCODE_DPB_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR),
    ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT(EXTAttachmentFeedbackLoopLayout.VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT),
    TENSOR_ALIASING_ARM(ARMTensors.VK_IMAGE_LAYOUT_TENSOR_ALIASING_ARM),
    VIDEO_ENCODE_QUANTIZATION_MAP_KHR(KHRVideoEncodeQuantizationMap.VK_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR),
    ZERO_INITIALIZED_EXT(EXTZeroInitializeDeviceMemory.VK_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT),
    DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR(DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL),
    DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR(DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL),
    SHADING_RATE_OPTIMAL_NV(FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR),
    RENDERING_LOCAL_READ_KHR(RENDERING_LOCAL_READ),
    DEPTH_ATTACHMENT_OPTIMAL_KHR(DEPTH_ATTACHMENT_OPTIMAL),
    DEPTH_READ_ONLY_OPTIMAL_KHR(DEPTH_READ_ONLY_OPTIMAL),
    STENCIL_ATTACHMENT_OPTIMAL_KHR(STENCIL_ATTACHMENT_OPTIMAL),
    STENCIL_READ_ONLY_OPTIMAL_KHR(STENCIL_READ_ONLY_OPTIMAL),
    READ_ONLY_OPTIMAL_KHR(READ_ONLY_OPTIMAL),
    ATTACHMENT_OPTIMAL_KHR(ATTACHMENT_OPTIMAL),
    ;

    private final int qualifier;
    VulkanicImageLayout(VulkanicImageLayout alias) {
        this.qualifier = alias.qualifier;
    }
    VulkanicImageLayout(int qualifier) {
        this.qualifier = qualifier;
    }
    public int qualifier() {
        return qualifier;
    }
}
