package net.flamgop.vulkanic.memory.image;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicImageCreateFlag implements Bitmaskable<Integer> {
    CREATE_SPARSE_BINDING(VK10.VK_IMAGE_CREATE_SPARSE_BINDING_BIT),
    CREATE_SPARSE_RESIDENCY(VK10.VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT),
    CREATE_SPARSE_ALIASED(VK10.VK_IMAGE_CREATE_SPARSE_ALIASED_BIT),
    CREATE_MUTABLE_FORMAT(VK10.VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT),
    CREATE_CUBE_COMPATIBLE(VK10.VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT),
    CREATE_ALIAS(VK11.VK_IMAGE_CREATE_ALIAS_BIT),
    CREATE_SPLIT_INSTANCE_BIND_REGIONS(VK11.VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT),
    CREATE_2D_ARRAY_COMPATIBLE(VK11.VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT),
    CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE(VK11.VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT),
    CREATE_EXTENDED_USAGE(VK11.VK_IMAGE_CREATE_EXTENDED_USAGE_BIT),
    CREATE_PROTECTED(VK11.VK_IMAGE_CREATE_PROTECTED_BIT),
    CREATE_DISJOINT(VK11.VK_IMAGE_CREATE_DISJOINT_BIT),
    CREATE_CORNER_SAMPLED_NV(NVCornerSampledImage.VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV),
    CREATE_DESCRIPTOR_HEAP_CAPTURE_REPLAY_EXT(EXTDescriptorHeap.VK_IMAGE_CREATE_DESCRIPTOR_HEAP_CAPTURE_REPLAY_BIT_EXT),
    CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_EXT(EXTSampleLocations.VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT),
    CREATE_SUBSAMPLED_EXT(EXTFragmentDensityMap.VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT),
    CREATE_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXT(EXTMultisampledRenderToSingleSampled.VK_IMAGE_CREATE_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_BIT_EXT),
    CREATE_2D_VIEW_COMPATIBLE_EXT(EXTImage2dViewOf3d.VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT),
    CREATE_VIDEO_PROFILE_INDEPENDENT_KHR(KHRVideoMaintenance1.VK_IMAGE_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR),
    CREATE_FRAGMENT_DENSITY_MAP_OFFSET_EXT(EXTFragmentDensityMap.VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT),
    CREATE_2D_ARRAY_COMPATIBLE_KHR(CREATE_2D_ARRAY_COMPATIBLE),
    CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_KHR(CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE),
    CREATE_EXTENDED_USAGE_KHR(CREATE_EXTENDED_USAGE),
    CREATE_DISJOINT_KHR(CREATE_DISJOINT),
    CREATE_ALIAS_KHR(CREATE_ALIAS),
    CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_EXT(CREATE_DESCRIPTOR_HEAP_CAPTURE_REPLAY_EXT),
    CREATE_FRAGMENT_DENSITY_MAP_OFFSET_QCOM(CREATE_FRAGMENT_DENSITY_MAP_OFFSET_EXT),

    ;

    private final int flag;
    VulkanicImageCreateFlag(VulkanicImageCreateFlag alias) {
        this.flag = alias.flag;
    }
    VulkanicImageCreateFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
