package net.flamgop.vulkanic.memory.platform;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicExternalMemoryHandleTypeFlag implements Bitmaskable<Integer> {
    OPAQUE_FD(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT),
    OPAQUE_WIN32(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT),
    OPAQUE_WIN32_KMT(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT),
    D3D11_TEXTURE(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT),
    D3D11_TEXTURE_KMT(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT),
    D3D12_HEAP(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT),
    D3D12_RESOURCE(VK11.VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT),

    DMA_BUF_EXT(EXTExternalMemoryDmaBuf.VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT),

    ANDROID_HARDWARE_BUFFER_ANDROID(ANDROIDExternalMemoryAndroidHardwareBuffer.VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID),

    HOST_ALLOCATION_EXT(EXTExternalMemoryHost.VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT),
    HOST_MAPPED_FOREIGN_MEMORY_EXT(EXTExternalMemoryHost.VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_MAPPED_FOREIGN_MEMORY_BIT_EXT),

//    ZIRCON_VMO_FUCHSIA() ??

    RDMA_ADDRESS_NV(NVExternalMemoryRdma.VK_EXTERNAL_MEMORY_HANDLE_TYPE_RDMA_ADDRESS_BIT_NV),

//    OH_NATIVE_BUFFER_OHOS() ??

//    SCREEN_BUFFER_QNX() ??

    MTLBUFFER_EXT(EXTExternalMemoryMetal.VK_EXTERNAL_MEMORY_HANDLE_TYPE_MTLBUFFER_BIT_EXT),
    MTLTEXTURE_EXT(EXTExternalMemoryMetal.VK_EXTERNAL_MEMORY_HANDLE_TYPE_MTLTEXTURE_BIT_EXT),
    MTLHEAP_EXT(EXTExternalMemoryMetal.VK_EXTERNAL_MEMORY_HANDLE_TYPE_MTLHEAP_BIT_EXT),
    ;
    private final int flag;
    VulkanicExternalMemoryHandleTypeFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
