package net.flamgop.vulkanic.reflect.bindings;

public enum SpvExecutionMode {
    SpvExecutionModeInvocations(0),
    SpvExecutionModeSpacingEqual(1),
    SpvExecutionModeSpacingFractionalEven(2),
    SpvExecutionModeSpacingFractionalOdd(3),
    SpvExecutionModeVertexOrderCw(4),
    SpvExecutionModeVertexOrderCcw(5),
    SpvExecutionModePixelCenterInteger(6),
    SpvExecutionModeOriginUpperLeft(7),
    SpvExecutionModeOriginLowerLeft(8),
    SpvExecutionModeEarlyFragmentTests(9),
    SpvExecutionModePointMode(10),
    SpvExecutionModeXfb(11),
    SpvExecutionModeDepthReplacing(12),
    SpvExecutionModeDepthGreater(14),
    SpvExecutionModeDepthLess(15),
    SpvExecutionModeDepthUnchanged(16),
    SpvExecutionModeLocalSize(17),
    SpvExecutionModeLocalSizeHint(18),
    SpvExecutionModeInputPoints(19),
    SpvExecutionModeInputLines(20),
    SpvExecutionModeInputLinesAdjacency(21),
    SpvExecutionModeTriangles(22),
    SpvExecutionModeInputTrianglesAdjacency(23),
    SpvExecutionModeQuads(24),
    SpvExecutionModeIsolines(25),
    SpvExecutionModeOutputVertices(26),
    SpvExecutionModeOutputPoints(27),
    SpvExecutionModeOutputLineStrip(28),
    SpvExecutionModeOutputTriangleStrip(29),
    SpvExecutionModeVecTypeHint(30),
    SpvExecutionModeContractionOff(31),
    SpvExecutionModeInitializer(33),
    SpvExecutionModeFinalizer(34),
    SpvExecutionModeSubgroupSize(35),
    SpvExecutionModeSubgroupsPerWorkgroup(36),
    SpvExecutionModeSubgroupsPerWorkgroupId(37),
    SpvExecutionModeLocalSizeId(38),
    SpvExecutionModeLocalSizeHintId(39),
    SpvExecutionModeNonCoherentColorAttachmentReadEXT(4169),
    SpvExecutionModeNonCoherentDepthAttachmentReadEXT(4170),
    SpvExecutionModeNonCoherentStencilAttachmentReadEXT(4171),
    SpvExecutionModeSubgroupUniformControlFlowKHR(4421),
    SpvExecutionModePostDepthCoverage(4446),
    SpvExecutionModeDenormPreserve(4459),
    SpvExecutionModeDenormFlushToZero(4460),
    SpvExecutionModeSignedZeroInfNanPreserve(4461),
    SpvExecutionModeRoundingModeRTE(4462),
    SpvExecutionModeRoundingModeRTZ(4463),
    SpvExecutionModeNonCoherentTileAttachmentReadQCOM(4489),
    SpvExecutionModeTileShadingRateQCOM(4490),
    SpvExecutionModeSubgroupSizeHalfQCOM(4507),
    SpvExecutionModeSubgroupSizeFullQCOM(4508),
    SpvExecutionModeEarlyAndLateFragmentTestsAMD(5017),
    SpvExecutionModeStencilRefReplacingEXT(5027),
    SpvExecutionModeCoalescingAMDX(5069),
    SpvExecutionModeIsApiEntryAMDX(5070),
    SpvExecutionModeMaxNodeRecursionAMDX(5071),
    SpvExecutionModeStaticNumWorkgroupsAMDX(5072),
    SpvExecutionModeShaderIndexAMDX(5073),
    SpvExecutionModeMaxNumWorkgroupsAMDX(5077),
    SpvExecutionModeStencilRefUnchangedFrontAMD(5079),
    SpvExecutionModeStencilRefGreaterFrontAMD(5080),
    SpvExecutionModeStencilRefLessFrontAMD(5081),
    SpvExecutionModeStencilRefUnchangedBackAMD(5082),
    SpvExecutionModeStencilRefGreaterBackAMD(5083),
    SpvExecutionModeStencilRefLessBackAMD(5084),
    SpvExecutionModeQuadDerivativesKHR(5088),
    SpvExecutionModeRequireFullQuadsKHR(5089),
    SpvExecutionModeSharesInputWithAMDX(5102),
    SpvExecutionModeArithmeticPoisonKHR(5157),
    SpvExecutionModeOutputLinesEXT(5269),
    SpvExecutionModeOutputLinesNV(5269),
    SpvExecutionModeOutputPrimitivesEXT(5270),
    SpvExecutionModeOutputPrimitivesNV(5270),
    SpvExecutionModeDerivativeGroupQuadsKHR(5289),
    SpvExecutionModeDerivativeGroupQuadsNV(5289),
    SpvExecutionModeDerivativeGroupLinearKHR(5290),
    SpvExecutionModeDerivativeGroupLinearNV(5290),
    SpvExecutionModeOutputTrianglesEXT(5298),
    SpvExecutionModeOutputTrianglesNV(5298),
    SpvExecutionModePixelInterlockOrderedEXT(5366),
    SpvExecutionModePixelInterlockUnorderedEXT(5367),
    SpvExecutionModeSampleInterlockOrderedEXT(5368),
    SpvExecutionModeSampleInterlockUnorderedEXT(5369),
    SpvExecutionModeShadingRateInterlockOrderedEXT(5370),
    SpvExecutionModeShadingRateInterlockUnorderedEXT(5371),
    SpvExecutionModeShader64BitIndexingEXT(5427),
    SpvExecutionModeSharedLocalMemorySizeINTEL(5618),
    SpvExecutionModeRoundingModeRTPINTEL(5620),
    SpvExecutionModeRoundingModeRTNINTEL(5621),
    SpvExecutionModeFloatingPointModeALTINTEL(5622),
    SpvExecutionModeFloatingPointModeIEEEINTEL(5623),
    SpvExecutionModeMaxWorkgroupSizeINTEL(5893),
    SpvExecutionModeMaxWorkDimINTEL(5894),
    SpvExecutionModeNoGlobalOffsetINTEL(5895),
    SpvExecutionModeNumSIMDWorkitemsINTEL(5896),
    SpvExecutionModeSchedulerTargetFmaxMhzINTEL(5903),
    SpvExecutionModeMaximallyReconvergesKHR(6023),
    SpvExecutionModeFPFastMathDefault(6028),
    SpvExecutionModeOpacityMicromapIdKHR(6031),
    SpvExecutionModeStreamingInterfaceINTEL(6154),
    SpvExecutionModeRegisterMapInterfaceINTEL(6160),
    SpvExecutionModeNamedBarrierCountINTEL(6417),
    SpvExecutionModeMaximumRegistersINTEL(6461),
    SpvExecutionModeMaximumRegistersIdINTEL(6462),
    SpvExecutionModeNamedMaximumRegistersINTEL(6463),
    SpvExecutionModeMax(2147483647);

    private final int value;

    SpvExecutionMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static SpvExecutionMode fromValue(int value) {
        for (var v : values()) {
            if (v.value == value) return v;
        }
        throw new IllegalArgumentException("Unknown SpvExecutionMode value: " + value);
    }
}
