package net.flamgop.vulkanic.reflect.bindings;

public enum SpvReflectUserType {
    SPV_REFLECT_USER_TYPE_INVALID(0),
    SPV_REFLECT_USER_TYPE_CBUFFER(1),
    SPV_REFLECT_USER_TYPE_TBUFFER(2),
    SPV_REFLECT_USER_TYPE_APPEND_STRUCTURED_BUFFER(3),
    SPV_REFLECT_USER_TYPE_BUFFER(4),
    SPV_REFLECT_USER_TYPE_BYTE_ADDRESS_BUFFER(5),
    SPV_REFLECT_USER_TYPE_CONSTANT_BUFFER(6),
    SPV_REFLECT_USER_TYPE_CONSUME_STRUCTURED_BUFFER(7),
    SPV_REFLECT_USER_TYPE_INPUT_PATCH(8),
    SPV_REFLECT_USER_TYPE_OUTPUT_PATCH(9),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_BUFFER(10),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_BYTE_ADDRESS_BUFFER(11),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_STRUCTURED_BUFFER(12),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_TEXTURE_1D(13),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_TEXTURE_1D_ARRAY(14),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_TEXTURE_2D(15),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_TEXTURE_2D_ARRAY(16),
    SPV_REFLECT_USER_TYPE_RASTERIZER_ORDERED_TEXTURE_3D(17),
    SPV_REFLECT_USER_TYPE_RAYTRACING_ACCELERATION_STRUCTURE(18),
    SPV_REFLECT_USER_TYPE_RW_BUFFER(19),
    SPV_REFLECT_USER_TYPE_RW_BYTE_ADDRESS_BUFFER(20),
    SPV_REFLECT_USER_TYPE_RW_STRUCTURED_BUFFER(21),
    SPV_REFLECT_USER_TYPE_RW_TEXTURE_1D(22),
    SPV_REFLECT_USER_TYPE_RW_TEXTURE_1D_ARRAY(23),
    SPV_REFLECT_USER_TYPE_RW_TEXTURE_2D(24),
    SPV_REFLECT_USER_TYPE_RW_TEXTURE_2D_ARRAY(25),
    SPV_REFLECT_USER_TYPE_RW_TEXTURE_3D(26),
    SPV_REFLECT_USER_TYPE_STRUCTURED_BUFFER(27),
    SPV_REFLECT_USER_TYPE_SUBPASS_INPUT(28),
    SPV_REFLECT_USER_TYPE_SUBPASS_INPUT_MS(29),
    SPV_REFLECT_USER_TYPE_TEXTURE_1D(30),
    SPV_REFLECT_USER_TYPE_TEXTURE_1D_ARRAY(31),
    SPV_REFLECT_USER_TYPE_TEXTURE_2D(32),
    SPV_REFLECT_USER_TYPE_TEXTURE_2D_ARRAY(33),
    SPV_REFLECT_USER_TYPE_TEXTURE_2DMS(34),
    SPV_REFLECT_USER_TYPE_TEXTURE_2DMS_ARRAY(35),
    SPV_REFLECT_USER_TYPE_TEXTURE_3D(36),
    SPV_REFLECT_USER_TYPE_TEXTURE_BUFFER(37),
    SPV_REFLECT_USER_TYPE_TEXTURE_CUBE(38),
    SPV_REFLECT_USER_TYPE_TEXTURE_CUBE_ARRAY(39);

    private final int value;

    SpvReflectUserType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static SpvReflectUserType fromValue(int value) {
        for (var v : values()) {
            if (v.value == value) return v;
        }
        throw new IllegalArgumentException("Unknown SpvReflectUserType value: " + value);
    }
}
