package net.flamgop.vulkanic.reflect.bindings;

public enum SpvReflectResult {
    SPV_REFLECT_RESULT_SUCCESS(0),
    SPV_REFLECT_RESULT_NOT_READY(1),
    SPV_REFLECT_RESULT_ERROR_PARSE_FAILED(2),
    SPV_REFLECT_RESULT_ERROR_ALLOC_FAILED(3),
    SPV_REFLECT_RESULT_ERROR_RANGE_EXCEEDED(4),
    SPV_REFLECT_RESULT_ERROR_NULL_POINTER(5),
    SPV_REFLECT_RESULT_ERROR_INTERNAL_ERROR(6),
    SPV_REFLECT_RESULT_ERROR_COUNT_MISMATCH(7),
    SPV_REFLECT_RESULT_ERROR_ELEMENT_NOT_FOUND(8),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_CODE_SIZE(9),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_MAGIC_NUMBER(10),
    SPV_REFLECT_RESULT_ERROR_SPIRV_UNEXPECTED_EOF(11),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ID_REFERENCE(12),
    SPV_REFLECT_RESULT_ERROR_SPIRV_SET_NUMBER_OVERFLOW(13),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_STORAGE_CLASS(14),
    SPV_REFLECT_RESULT_ERROR_SPIRV_RECURSION(15),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_INSTRUCTION(16),
    SPV_REFLECT_RESULT_ERROR_SPIRV_UNEXPECTED_BLOCK_DATA(17),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_BLOCK_MEMBER_REFERENCE(18),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ENTRY_POINT(19),
    SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_EXECUTION_MODE(20),
    SPV_REFLECT_RESULT_ERROR_SPIRV_MAX_RECURSIVE_EXCEEDED(21);

    private final int value;

    SpvReflectResult(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static SpvReflectResult fromValue(int value) {
        for (var v : values()) {
            if (v.value == value) return v;
        }
        throw new IllegalArgumentException("Unknown SpvReflectResult value: " + value);
    }
}
