package net.flamgop.vulkanic.exception;

import org.lwjgl.vulkan.*;

import java.util.HashMap;
import java.util.Map;

public enum VulkanicResult {
    SUCCESS(VK10.VK_SUCCESS),
    NOT_READY(VK10.VK_NOT_READY),
    TIMEOUT(VK10.VK_TIMEOUT),
    EVENT_SET(VK10.VK_EVENT_SET),
    EVENT_RESET(VK10.VK_EVENT_RESET),
    INCOMPLETE(VK10.VK_INCOMPLETE),
    ERROR_OUT_OF_HOST_MEMORY(VK10.VK_ERROR_OUT_OF_HOST_MEMORY),
    ERROR_OUT_OF_DEVICE_MEMORY(VK10.VK_ERROR_OUT_OF_DEVICE_MEMORY),
    ERROR_INITIALIZATION_FAILED(VK10.VK_ERROR_INITIALIZATION_FAILED),
    ERROR_DEVICE_LOST(VK10.VK_ERROR_DEVICE_LOST),
    ERROR_MEMORY_MAP_FAILED(VK10.VK_ERROR_MEMORY_MAP_FAILED),
    ERROR_LAYER_NOT_PRESENT(VK10.VK_ERROR_LAYER_NOT_PRESENT),
    ERROR_EXTENSION_NOT_PRESENT(VK10.VK_ERROR_EXTENSION_NOT_PRESENT),
    ERROR_FEATURE_NOT_PRESENT(VK10.VK_ERROR_FEATURE_NOT_PRESENT),
    ERROR_INCOMPATIBLE_DRIVER(VK10.VK_ERROR_INCOMPATIBLE_DRIVER),
    ERROR_TOO_MANY_OBJECTS(VK10.VK_ERROR_TOO_MANY_OBJECTS),
    ERROR_FORMAT_NOT_SUPPORTED(VK10.VK_ERROR_FORMAT_NOT_SUPPORTED),
    ERROR_FRAGMENTED_POOL(VK10.VK_ERROR_FRAGMENTED_POOL),
    ERROR_UNKNOWN(VK10.VK_ERROR_UNKNOWN),
    ERROR_VALIDATION_FAILED(VK10.VK_ERROR_VALIDATION_FAILED),

    ERROR_OUT_OF_POOL_MEMORY(VK11.VK_ERROR_OUT_OF_POOL_MEMORY),
    ERROR_INVALID_EXTERNAL_HANDLE(VK11.VK_ERROR_INVALID_EXTERNAL_HANDLE),

    ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS(VK12.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS),
    ERROR_FRAGMENTATION(VK12.VK_ERROR_FRAGMENTATION),

    PIPELINE_COMPILE_REQUIRED(VK13.VK_PIPELINE_COMPILE_REQUIRED),

    ERROR_NOT_PERMITTED(VK14.VK_ERROR_NOT_PERMITTED),

    ERROR_SURFACE_LOST_KHR(KHRSurface.VK_ERROR_SURFACE_LOST_KHR),
    ERROR_NATIVE_WINDOW_IN_USE_KHR(KHRSurface.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR),

    SUBOPTIMAL_KHR(KHRSwapchain.VK_SUBOPTIMAL_KHR),
    ERROR_OUT_OF_DATE_KHR(KHRSwapchain.VK_ERROR_OUT_OF_DATE_KHR),

    ERROR_INCOMPATIBLE_DISPLAY_KHR(KHRDisplaySwapchain.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR),

    ERROR_INVALID_SHADER_NV(NVGLSLShader.VK_ERROR_INVALID_SHADER_NV),

    ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR),
    ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR),
    ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR),
    ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR),
    ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR),
    ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR(KHRVideoQueue.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR),

    ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT(EXTImageDrmFormatModifier.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT),

    ERROR_PRESENT_TIMING_QUEUE_FULL_EXT(EXTPresentTiming.VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT),

    ERROR_FULLSCREEN_EXCLUSIVE_MODE_LOST_EXT(EXTFullScreenExclusive.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT),

    THREAD_IDLE_KHR(KHRDeferredHostOperations.VK_THREAD_IDLE_KHR),
    THREAD_DONE_KHR(KHRDeferredHostOperations.VK_THREAD_DONE_KHR),
    OPERATION_DEFERRED_KHR(KHRDeferredHostOperations.VK_OPERATION_DEFERRED_KHR),
    OPERATION_NOT_DEFERRED_KHR(KHRDeferredHostOperations.VK_OPERATION_NOT_DEFERRED_KHR),

    ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR(KHRVideoEncodeQueue.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR),

    ERROR_COMPRESSION_EXHAUSTED_EXT(EXTImageCompressionControl.VK_ERROR_COMPRESSION_EXHAUSTED_EXT),

    INCOMPATIBLE_SHADER_BINARY_EXT(EXTShaderObject.VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT),

    PIPELINE_BINARY_MISSING_KHR(KHRPipelineBinary.VK_PIPELINE_BINARY_MISSING_KHR),
    ERROR_NOT_ENOUGH_SPACE_KHR(KHRPipelineBinary.VK_ERROR_NOT_ENOUGH_SPACE_KHR),

    ;

    private static final Map<Integer, VulkanicResult> VALUE_MAP = new HashMap<>();

    static {
        for (VulkanicResult value : VulkanicResult.values()) {
            VALUE_MAP.put(value.qualifier(), value);
        }
    }

    public static VulkanicResult valueOf(int result) {
        if (!VALUE_MAP.containsKey(result)) throw new RuntimeException(String.format("BAD VULKANIC RESULT INPUT!! %s", result));
        return VALUE_MAP.get(result);
    }

    private final int qualifier;

    VulkanicResult(int qualifier) {
        this.qualifier = qualifier;
    }

    public int qualifier() {
        return qualifier;
    }

    public boolean success() {
        return this == SUCCESS;
    }
}
