package net.flamgop.vulkanic.pipeline.graphics;

import org.lwjgl.vulkan.*;

public enum VulkanicDynamicState {
    VIEWPORT(VK10.VK_DYNAMIC_STATE_VIEWPORT),
    SCISSOR(VK10.VK_DYNAMIC_STATE_SCISSOR),
    LINE_WIDTH(VK10.VK_DYNAMIC_STATE_LINE_WIDTH),
    DEPTH_BIAS(VK10.VK_DYNAMIC_STATE_DEPTH_BIAS),
    BLEND_CONSTANTS(VK10.VK_DYNAMIC_STATE_BLEND_CONSTANTS),
    DEPTH_BOUNDS(VK10.VK_DYNAMIC_STATE_DEPTH_BOUNDS),
    STENCIL_COMPARE_MASK(VK10.VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK),
    STENCIL_WRITE_MASK(VK10.VK_DYNAMIC_STATE_STENCIL_WRITE_MASK),
    STENCIL_REFERENCE(VK10.VK_DYNAMIC_STATE_STENCIL_REFERENCE),

    CULL_MODE(VK13.VK_DYNAMIC_STATE_CULL_MODE),
    FRONT_FACE(VK13.VK_DYNAMIC_STATE_FRONT_FACE),
    PRIMITIVE_TOPOLOGY(VK13.VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY),
    VIEWPORT_WITH_COUNT(VK13.VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT),
    SCISSOR_WITH_COUNT(VK13.VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT),
    VERTEX_INPUT_BINDING_STRIDE(VK13.VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE),
    DEPTH_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE),
    DEPTH_WRITE_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE),
    DEPTH_COMPARE_OP(VK13.VK_DYNAMIC_STATE_DEPTH_COMPARE_OP),
    DEPTH_BOUNDS_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE),
    STENCIL_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE),
    STENCIL_OP(VK13.VK_DYNAMIC_STATE_STENCIL_OP),
    RASTERIZER_DISCARD_ENABLE(VK13.VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE),
    DEPTH_BIAS_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE),
    PRIMITIVE_RESTART_ENABLE(VK13.VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE),

    LINE_STIPPLE(VK14.VK_DYNAMIC_STATE_LINE_STIPPLE),

    VIEWPORT_W_SCALING_NV(NVClipSpaceWScaling.VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV),

    DISCARD_RECTANGLE_EXT(EXTDiscardRectangles.VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT),
    DISCARD_RECTANGLE_ENABLE_EXT(EXTDiscardRectangles.VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT),
    DISCARD_RECTANGLE_MODE_EXT(EXTDiscardRectangles.VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT),

    SAMPLE_LOCATIONS_EXT(EXTSampleLocations.VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT),

    RAY_TRACING_PIPELINE_STACK_SIZE_KHR(KHRRayTracingPipeline.VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR),

    VIEWPORT_SHADING_RATE_PALETTE_NV(NVShadingRateImage.VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV),
    VIEWPORT_COARSE_SAMPLE_ORDER_NV(NVShadingRateImage.VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV),

    EXCLUSIVE_SCISSOR_ENABLE_NV(NVScissorExclusive.VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV),
    EXCLUSIVE_SCISSOR_NV(NVScissorExclusive.VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV),

    FRAGMENT_SHADING_RATE_KHR(KHRFragmentShadingRate.VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR),

    VERTEX_INPUT_EXT(EXTVertexInputDynamicState.VK_DYNAMIC_STATE_VERTEX_INPUT_EXT),

    PATCH_CONTROL_POINTS_EXT(EXTExtendedDynamicState2.VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT),
    LOGIC_OP_EXT(EXTExtendedDynamicState2.VK_DYNAMIC_STATE_LOGIC_OP_EXT),

    COLOR_WRITE_ENABLE_EXT(EXTColorWriteEnable.VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT),

    DEPTH_CLAMP_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT),
    POLYGON_MODE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_POLYGON_MODE_EXT),
    RASTERIZATION_SAMPLES_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT),
    SAMPLE_MASK_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_SAMPLE_MASK_EXT),
    ALPHA_TO_COVERAGE_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT),
    ALPHA_TO_ONE_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT),
    LOGIC_OP_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT),
    COLOR_BLEND_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT),
    COLOR_BLEND_EQUATION_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT),
    COLOR_WRITE_MASK_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT),

    // with VK_KHR_maintenance2 or VK_VERSION_1_1
    TESSELLATION_DOMAIN_ORIGIN_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT),
    // with VK_EXT_transform_feedback
    RASTERIZATION_STREAM_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT),
    // with VK_EXT_conservative_rasterization
    CONSERVATIVE_RASTERIZATION_MODE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT),
    EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT),
    // with VK_EXT_depth_clip_enable
    DEPTH_CLIP_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT),
    // with VK_EXT_sample_locations
    SAMPLE_LOCATIONS_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT),
    // with VK_EXT_blend_operation_advanced
    COLOR_BLEND_ADVANCED_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT),
    // with VK_EXT_provoking_vertex
    PROVOKING_VERTEX_MODE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT),
    // with VK_EXT_line_rasterization
    LINE_RASTERIZATION_MODE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT),
    LINE_STIPPLE_ENABLE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT),
    // with VK_EXT_depth_clip_control
    DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT),
    // with VK_NV_clip_space_w_scaling
    VIEWPORT_W_SCALING_ENABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV),
    // with VK_NV_viewport_swizzle
    VIEWPORT_SWIZZLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV),
    // with VK_NV_fragment_coverage_to_color
    COVERAGE_TO_COLOR_ENABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV),
    COVERAGE_TO_COLOR_LOCATION_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV),
    // with VK_NV_framebuffer_mixed_samples
    COVERAGE_MODULATION_MODE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV),
    COVERAGE_MODULATION_TABLE_ENABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV),
    COVERAGE_MODULATION_TABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV),
    // with VK_NV_shading_rate_image
    SHADING_RATE_IMAGE_ENABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV),
    // with VK_NV_representative_fragment_test
    REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV),
    // with VK_NV_coverage_reduction_mode
    COVERAGE_REDUCTION_MODE_NV(EXTExtendedDynamicState3.VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV),

    ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT(EXTAttachmentFeedbackLoopDynamicState.VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT),

    DEPTH_CLAMP_RANGE_EXT(EXTDepthClampControl.VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT),

    ;

    private final int qualifier;
    VulkanicDynamicState(int qualifier) {
        this.qualifier = qualifier;
    }
    public int qualifier() {
        return qualifier;
    }
}
