package net.flamgop.vulkanic.sync;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.EXTMeshShader;
import org.lwjgl.vulkan.HUAWEIClusterCullingShader;
import org.lwjgl.vulkan.VK10;

public enum VulkanicQueryPipelineStatisticFlag implements Bitmaskable<Integer> {
    INPUT_ASSEMBLY_VERTICES(VK10.VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT),
    INPUT_ASSEMBLY_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT),
    VERTEX_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT),
    GEOMETRY_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT),
    GEOMETRY_SHADER_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT),
    CLIPPING_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT),
    CLIPPING_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT),
    FRAGMENT_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT),
    TESSELLATION_CONTROL_SHADER_PATCHES(VK10.VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT),
    TESSELLATION_EVALUATION_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT),
    COMPUTE_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT),

    TASK_SHADER_INVOCATIONS_EXT(EXTMeshShader.VK_QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT),
    MESH_SHADER_INVOCATIONS_EXT(EXTMeshShader.VK_QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT),

    CLUSTER_CULLING_SHADER_INVOCATIONS_HUAWEI(HUAWEIClusterCullingShader.VK_QUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI),

    ;
    private final int flag;
    VulkanicQueryPipelineStatisticFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
