package net.flamgop.vulkanic.memory.format;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.intellij.lang.annotations.MagicConstant;
import org.lwjgl.vulkan.*;

import java.util.EnumSet;
import java.util.Set;

public enum VulkanicFormatFeatureFlag implements Bitmaskable<Long> {
    SAMPLED_IMAGE(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT),
    STORAGE_IMAGE(VK13.VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT),
    STORAGE_IMAGE_ATOMIC(VK13.VK_FORMAT_FEATURE_2_STORAGE_IMAGE_ATOMIC_BIT),
    UNIFORM_TEXEL_BUFFER(VK13.VK_FORMAT_FEATURE_2_UNIFORM_TEXEL_BUFFER_BIT),
    STORAGE_TEXEL_BUFFER(VK13.VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_BIT),
    STORAGE_TEXEL_BUFFER_ATOMIC(VK13.VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_ATOMIC_BIT),
    VERTEX_BUFFER(VK13.VK_FORMAT_FEATURE_2_VERTEX_BUFFER_BIT),
    COLOR_ATTACHMENT(VK13.VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT),
    COLOR_ATTACHMENT_BLEND(VK13.VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT),
    DEPTH_STENCIL_ATTACHMENT(VK13.VK_FORMAT_FEATURE_2_DEPTH_STENCIL_ATTACHMENT_BIT),
    BLIT_SRC(VK13.VK_FORMAT_FEATURE_2_BLIT_SRC_BIT),
    BLIT_DST(VK13.VK_FORMAT_FEATURE_2_BLIT_DST_BIT),
    SAMPLED_IMAGE_FILTER_LINEAR(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT),
    TRANSFER_SRC(VK13.VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT),
    TRANSFER_DST(VK13.VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT),
    SAMPLED_IMAGE_FILTER_MINMAX(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT),
    MIDPOINT_CHROMA_SAMPLES(VK13.VK_FORMAT_FEATURE_2_MIDPOINT_CHROMA_SAMPLES_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT),
    DISJOINT(VK13.VK_FORMAT_FEATURE_2_DISJOINT_BIT),
    COSITED_CHROMA_SAMPLES(VK13.VK_FORMAT_FEATURE_2_COSITED_CHROMA_SAMPLES_BIT),
    STORAGE_READ_WITHOUT_FORMAT(VK13.VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT),
    STORAGE_WRITE_WITHOUT_FORMAT(VK13.VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT),
    SAMPLED_IMAGE_DEPTH_COMPARISON(VK13.VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT),

    HOST_IMAGE_TRANSFER(VK14.VK_FORMAT_FEATURE_2_HOST_IMAGE_TRANSFER_BIT),

    VIDEO_DECODE_OUTPUT_KHR(KHRVideoDecodeQueue.VK_FORMAT_FEATURE_2_VIDEO_DECODE_OUTPUT_BIT_KHR),
    VIDEO_DECODE_DPB_KHR(KHRVideoDecodeQueue.VK_FORMAT_FEATURE_2_VIDEO_DECODE_DPB_BIT_KHR),

    ACCELERATION_STRUCTURE_VERTEX_BUFFER_KHR(KHRAccelerationStructure.VK_FORMAT_FEATURE_2_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR),

    SAMPLED_IMAGE_FILTER_CUBIC(EXTFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT), // NOTE: this is legacy, but it's the same long value.

    FRAGMENT_DENSITY_MAP_EXT(EXTFragmentDensityMap.VK_FORMAT_FEATURE_2_FRAGMENT_DENSITY_MAP_BIT_EXT),

    FRAGMENT_SHADING_RATE_ATTACHMENT_KHR(KHRFragmentShadingRate.VK_FORMAT_FEATURE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR),

    HOST_IMAGE_TRANSFER_EXT(EXTHostImageCopy.VK_FORMAT_FEATURE_2_HOST_IMAGE_TRANSFER_BIT_EXT),

    VIDEO_ENCODE_INPUT_KHR(KHRVideoEncodeQueue.VK_FORMAT_FEATURE_2_VIDEO_ENCODE_INPUT_BIT_KHR),
    VIDEO_ENCODE_DPB_KHR(KHRVideoEncodeQueue.VK_FORMAT_FEATURE_2_VIDEO_ENCODE_DPB_BIT_KHR),

    ACCELERATION_STRUCTURE_RADIUS_BUFFER_NV(NVRayTracingLinearSweptSpheres.VK_FORMAT_FEATURE_2_ACCELERATION_STRUCTURE_RADIUS_BUFFER_BIT_NV),

    LINEAR_COLOR_ATTACHMENT_NV(NVLinearColorAttachment.VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV),

    WEIGHT_IMAGE_QCOM(QCOMImageProcessing.VK_FORMAT_FEATURE_2_WEIGHT_IMAGE_BIT_QCOM),
    WEIGHT_SAMPLED_IMAGE_QCOM(QCOMImageProcessing.VK_FORMAT_FEATURE_2_WEIGHT_SAMPLED_IMAGE_BIT_QCOM),
    BLOCK_MATCHING_QCOM(QCOMImageProcessing.VK_FORMAT_FEATURE_2_BLOCK_MATCHING_BIT_QCOM),
    BOX_FILTER_SAMPLED_QCOM(QCOMImageProcessing.VK_FORMAT_FEATURE_2_BOX_FILTER_SAMPLED_BIT_QCOM),

    TENSOR_SHADER_ARM(ARMTensors.VK_FORMAT_FEATURE_2_TENSOR_SHADER_BIT_ARM),
    TENSOR_IMAGE_ALIASING_ARM(ARMTensors.VK_FORMAT_FEATURE_2_TENSOR_IMAGE_ALIASING_BIT_ARM),

    OPTICAL_FLOW_IMAGE_NV(NVOpticalFlow.VK_FORMAT_FEATURE_2_OPTICAL_FLOW_IMAGE_BIT_NV),
    OPTICAL_FLOW_VECTOR_NV(NVOpticalFlow.VK_FORMAT_FEATURE_2_OPTICAL_FLOW_VECTOR_BIT_NV),
    OPTICAL_FLOW_COST_NV(NVOpticalFlow.VK_FORMAT_FEATURE_2_OPTICAL_FLOW_COST_BIT_NV),

    TENSOR_DATA_GRAPH_ARM(ARMDataGraph.VK_FORMAT_FEATURE_2_TENSOR_DATA_GRAPH_BIT_ARM),

    COPY_IMAGE_INDIRECT_DST_KHR(KHRCopyMemoryIndirect.VK_FORMAT_FEATURE_2_COPY_IMAGE_INDIRECT_DST_BIT_KHR),

    VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_KHR(KHRVideoEncodeQuantizationMap.VK_FORMAT_FEATURE_2_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR),
    VIDEO_ENCODE_EMPHASIS_MAP_KHR(KHRVideoEncodeQuantizationMap.VK_FORMAT_FEATURE_2_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR),

    // Provided by VK_IMG_filter_linear_2d
    SAMPLED_IMAGE_FILTER_LINEAR_2D_IMG(0x200000000000L),

    DEPTH_COPY_ON_COMPUTE_QUEUE_KHR(KHRMaintenance10.VK_FORMAT_FEATURE_2_DEPTH_COPY_ON_COMPUTE_QUEUE_BIT_KHR),
    DEPTH_COPY_ON_TRANSFER_QUEUE_KHR(KHRMaintenance10.VK_FORMAT_FEATURE_2_DEPTH_COPY_ON_TRANSFER_QUEUE_BIT_KHR),

    STENCIL_COPY_ON_COMPUTE_QUEUE_KHR(KHRMaintenance10.VK_FORMAT_FEATURE_2_STENCIL_COPY_ON_COMPUTE_QUEUE_BIT_KHR),
    STENCIL_COPY_ON_TRANSFER_QUEUE_KHR(KHRMaintenance10.VK_FORMAT_FEATURE_2_STENCIL_COPY_ON_TRANSFER_QUEUE_BIT_KHR),

    // Provided by VK_ARM_data_graph_optical_flow
    DATA_GRAPH_OPTICAL_FLOW_IMAGE_ARM(0x100000000000000L),
    DATA_GRAPH_OPTICAL_FLOW_VECTOR_ARM(0x200000000000000L),
    DATA_GRAPH_OPTICAL_FLOW_COST_ARM(0x400000000000000L)
    ;

    // this exists purely to convert from legacy integer VkFormatFeatureFlagBits to VkFormatFeatureFlagBits2, so I don't have to maintain multiple enums.
    @MagicConstant(intValues = {
            VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT,
            VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT,
            VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT,
            VK10.VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT,
            VK10.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT,
            VK10.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT,
            VK10.VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT,
            VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT,
            VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT,
            VK10.VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT,
            VK10.VK_FORMAT_FEATURE_BLIT_SRC_BIT,
            VK10.VK_FORMAT_FEATURE_BLIT_DST_BIT,
            VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT,

            VK11.VK_FORMAT_FEATURE_TRANSFER_SRC_BIT,
            VK11.VK_FORMAT_FEATURE_TRANSFER_DST_BIT,
            VK11.VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT,
            VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT,
            VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT,
            VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT,
            VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT,
            VK11.VK_FORMAT_FEATURE_DISJOINT_BIT,
            VK11.VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT,

            VK12.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT,

            KHRVideoDecodeQueue.VK_FORMAT_FEATURE_VIDEO_DECODE_OUTPUT_BIT_KHR,
            KHRVideoDecodeQueue.VK_FORMAT_FEATURE_VIDEO_DECODE_DPB_BIT_KHR,

            KHRAccelerationStructure.VK_FORMAT_FEATURE_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR,

            EXTFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT,

            EXTFragmentDensityMap.VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT,

            KHRFragmentShadingRate.VK_FORMAT_FEATURE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,

            KHRVideoEncodeQueue.VK_FORMAT_FEATURE_VIDEO_ENCODE_INPUT_BIT_KHR,
            KHRVideoEncodeQueue.VK_FORMAT_FEATURE_VIDEO_ENCODE_DPB_BIT_KHR,

            // aliases
            IMGFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG,

            KHRMaintenance1.VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR,
            KHRMaintenance1.VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR,

            EXTSamplerFilterMinmax.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT,

            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_DISJOINT_BIT_KHR,
            KHRSamplerYcbcrConversion.VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR,
    })
    public static VulkanicFormatFeatureFlag fromLegacyValue(int constant) {
        return switch (constant) {
            case VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT -> SAMPLED_IMAGE;
            case VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT -> STORAGE_IMAGE;
            case VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT -> STORAGE_IMAGE_ATOMIC;
            case VK10.VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT -> UNIFORM_TEXEL_BUFFER;
            case VK10.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT -> STORAGE_TEXEL_BUFFER;
            case VK10.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT -> STORAGE_TEXEL_BUFFER_ATOMIC;
            case VK10.VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT -> VERTEX_BUFFER;
            case VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT -> COLOR_ATTACHMENT;
            case VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT -> COLOR_ATTACHMENT_BLEND;
            case VK10.VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT -> DEPTH_STENCIL_ATTACHMENT;
            case VK10.VK_FORMAT_FEATURE_BLIT_SRC_BIT -> BLIT_SRC;
            case VK10.VK_FORMAT_FEATURE_BLIT_DST_BIT -> BLIT_DST;
            case VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT -> SAMPLED_IMAGE_FILTER_LINEAR;

            case VK11.VK_FORMAT_FEATURE_TRANSFER_SRC_BIT -> TRANSFER_SRC;
            case VK11.VK_FORMAT_FEATURE_TRANSFER_DST_BIT -> TRANSFER_DST;
            case VK11.VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT -> MIDPOINT_CHROMA_SAMPLES;
            case VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT -> SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER;
            case VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT -> SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER;
            case VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT -> SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT;
            case VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT -> SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE;
            case VK11.VK_FORMAT_FEATURE_DISJOINT_BIT -> DISJOINT;
            case VK11.VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT -> COSITED_CHROMA_SAMPLES;

            case VK12.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT -> SAMPLED_IMAGE_FILTER_MINMAX;

            case KHRVideoDecodeQueue.VK_FORMAT_FEATURE_VIDEO_DECODE_OUTPUT_BIT_KHR -> VIDEO_DECODE_OUTPUT_KHR;
            case KHRVideoDecodeQueue.VK_FORMAT_FEATURE_VIDEO_DECODE_DPB_BIT_KHR -> VIDEO_DECODE_DPB_KHR;

            case KHRAccelerationStructure.VK_FORMAT_FEATURE_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR -> ACCELERATION_STRUCTURE_VERTEX_BUFFER_KHR;

            case EXTFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT -> SAMPLED_IMAGE_FILTER_CUBIC;

            case EXTFragmentDensityMap.VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT -> FRAGMENT_DENSITY_MAP_EXT;

            case KHRFragmentShadingRate.VK_FORMAT_FEATURE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR -> FRAGMENT_SHADING_RATE_ATTACHMENT_KHR;

            case KHRVideoEncodeQueue.VK_FORMAT_FEATURE_VIDEO_ENCODE_INPUT_BIT_KHR -> VIDEO_ENCODE_INPUT_KHR;
            case KHRVideoEncodeQueue.VK_FORMAT_FEATURE_VIDEO_ENCODE_DPB_BIT_KHR -> VIDEO_ENCODE_DPB_KHR;

            default -> throw new IllegalArgumentException("Unknown format feature flag: " + constant);
        };
    }

    public static Set<VulkanicFormatFeatureFlag> decomposeLegacyBitmask(int mask) {
        Set<VulkanicFormatFeatureFlag> flags = EnumSet.noneOf(VulkanicFormatFeatureFlag.class);
        while (mask != 0) {
            int lowestBit = Integer.lowestOneBit(mask);
            flags.add(fromLegacyValue(lowestBit));
            mask ^= lowestBit;
        }
        return flags;
    }

    private final long flag;
    VulkanicFormatFeatureFlag(long flag) {
        this.flag = flag;
    }

    @Override
    public Long flag() {
        return flag;
    }
}
