package net.flamgop.vulkanic.pipeline;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicShaderStage implements Bitmaskable<Integer> {
    VERTEX(VK10.VK_SHADER_STAGE_VERTEX_BIT),
    TESSELLATION_CONTROL(VK10.VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT),
    TESSELLATION_EVALUATION(VK10.VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT),
    GEOMETRY(VK10.VK_SHADER_STAGE_GEOMETRY_BIT),
    FRAGMENT(VK10.VK_SHADER_STAGE_FRAGMENT_BIT),
    COMPUTE(VK10.VK_SHADER_STAGE_COMPUTE_BIT),
    ALL_GRAPHICS(VK10.VK_SHADER_STAGE_ALL_GRAPHICS),
    ALL(VK10.VK_SHADER_STAGE_ALL),
    RAYGEN_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_RAYGEN_BIT_KHR),
    ANY_HIT_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_ANY_HIT_BIT_KHR),
    CLOSEST_HIT_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR),
    MISS_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_MISS_BIT_KHR),
    INTERSECTION_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_INTERSECTION_BIT_KHR),
    CALLABLE_KHR(KHRRayTracingPipeline.VK_SHADER_STAGE_CALLABLE_BIT_KHR),
    TASK_EXT(EXTMeshShader.VK_SHADER_STAGE_TASK_BIT_EXT),
    MESH_EXT(EXTMeshShader.VK_SHADER_STAGE_MESH_BIT_EXT),
    SUBPASS_SHADING_HUAWEI(HUAWEISubpassShading.VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI),
    CLUSTER_CULLING_HUAWEI(HUAWEIClusterCullingShader.VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI),
    RAYGEN_NV(NVRayTracing.VK_SHADER_STAGE_RAYGEN_BIT_NV),
    ANY_HIT_NV(NVRayTracing.VK_SHADER_STAGE_ANY_HIT_BIT_NV),
    CLOSEST_HIT_NV(NVRayTracing.VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV),
    MISS_NV(NVRayTracing.VK_SHADER_STAGE_MISS_BIT_NV),
    INTERSECTION_NV(NVRayTracing.VK_SHADER_STAGE_INTERSECTION_BIT_NV),
    CALLABLE_NV(NVRayTracing.VK_SHADER_STAGE_CALLABLE_BIT_NV),
    TASK_NV(NVMeshShader.VK_SHADER_STAGE_TASK_BIT_NV),
    MESH_NV(NVMeshShader.VK_SHADER_STAGE_MESH_BIT_NV),
    ;

    private final int flag;
    VulkanicShaderStage(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
