package net.flamgop.vulkanic.pipeline;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicPipelineCreateFlag implements Bitmaskable<Integer> {
    DISABLE_OPTIMIZATION(VK10.VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT),
    ALLOW_DERIVATIVES(VK10.VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT),
    DERIVATIVE(VK10.VK_PIPELINE_CREATE_DERIVATIVE_BIT),

    DISPATCH_BASE(VK11.VK_PIPELINE_CREATE_DISPATCH_BASE_BIT),
    VIEW_INDEX_FROM_DEVICE_INDEX(VK11.VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT),

    FAIL_ON_PIPELINE_COMPILE_REQUIRED(VK13.VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT),
    EARLY_RETURN_ON_FAILURE(VK13.VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT),

    NO_PROTECTED_ACCESS(VK14.VK_PIPELINE_CREATE_NO_PROTECTED_ACCESS_BIT),
    PROTECTED_ACCESS_ONLY(VK14.VK_PIPELINE_CREATE_PROTECTED_ACCESS_ONLY_BIT),

    RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_ANY_HIT_SHADERS_BIT_KHR),
    RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_CLOSEST_HIT_SHADERS_BIT_KHR),
    RAY_TRACING_NO_NULL_MISS_SHADERS_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_MISS_SHADERS_BIT_KHR),
    RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_NO_NULL_INTERSECTION_SHADERS_BIT_KHR),
    RAY_TRACING_SKIP_TRIANGLES_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_SKIP_TRIANGLES_BIT_KHR),
    RAY_TRACING_SKIP_AABBS_KHR(KHRRayTracingPipeline.VK_PIPELINE_CREATE_RAY_TRACING_SKIP_AABBS_BIT_KHR),

    DEFER_COMPILE_NV(NVRayTracing.VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV),

    RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_EXT(EXTFragmentDensityMap.VK_PIPELINE_CREATE_RENDERING_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT),

    RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_KHR(KHRFragmentShadingRate.VK_PIPELINE_CREATE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR),

    CAPTURE_STATISTICS_KHR(KHRPipelineExecutableProperties.VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR),
    CAPTURE_INTERNAL_REPRESENTATIONS_KHR(KHRPipelineExecutableProperties.VK_PIPELINE_CREATE_CAPTURE_INTERNAL_REPRESENTATIONS_BIT_KHR),

    INDIRECT_BINDABLE_NV(NVDeviceGeneratedCommands.VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV),

    LIBRARY_KHR(KHRPipelineLibrary.VK_PIPELINE_CREATE_LIBRARY_BIT_KHR),

    DESCRIPTOR_BUFFER_EXT(EXTDescriptorBuffer.VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT),

    RETAIN_LINK_TIME_OPTIMIZATION_INFO_EXT(EXTGraphicsPipelineLibrary.VK_PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT),
    LINK_TIME_OPTIMIZATION_EXT(EXTGraphicsPipelineLibrary.VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT),

    RAY_TRACING_ALLOW_MOTION_NV(NVRayTracingMotionBlur.VK_PIPELINE_CREATE_RAY_TRACING_ALLOW_MOTION_BIT_NV),

    COLOR_ATTACHMENT_FEEDBACK_LOOP_EXT(EXTAttachmentFeedbackLoopLayout.VK_PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT),
    DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_EXT(EXTAttachmentFeedbackLoopLayout.VK_PIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT),

    RAY_TRACING_DISPLACEMENT_MICROMAP_NV(NVDisplacementMicromap.VK_PIPELINE_CREATE_RAY_TRACING_DISPLACEMENT_MICROMAP_BIT_NV),

    RAY_TRACING_OPACITY_MICROMAP_KHR(0x01000000) // can't find a class for this? the extension is VK_KHR_opacity_micromap

    ;

    private final int flag;
    VulkanicPipelineCreateFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
