package net.flamgop.vulkanic.pipeline;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicPipelineStageFlag implements Bitmaskable<Long> {
    NONE(VK13.VK_PIPELINE_STAGE_2_NONE),
    TOP_OF_PIPE(VK13.VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT),
    DRAW_INDIRECT(VK13.VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT),
    VERTEX_INPUT(VK13.VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT),
    VERTEX_SHADER(VK13.VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT),
    TESSELLATION_CONTROL_SHADER(VK13.VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT),
    TESSELLATION_EVALUATION_SHADER(VK13.VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT),
    GEOMETRY_SHADER(VK13.VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT),
    FRAGMENT_SHADER(VK13.VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT),
    EARLY_FRAGMENT_TESTS(VK13.VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT),
    LATE_FRAGMENT_TESTS(VK13.VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT),
    COLOR_ATTACHMENT_OUTPUT(VK13.VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT),
    COMPUTE_SHADER(VK13.VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT),
    ALL_TRANSFER(VK13.VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT), // NOTE: ALL_TRANSFER is an alias for TRANSFER
    BOTTOM_OF_PIPE(VK13.VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT),
    HOST(VK13.VK_PIPELINE_STAGE_2_HOST_BIT),
    ALL_GRAPHICS(VK13.VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT),
    ALL_COMMANDS(VK13.VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT),
    COPY(VK13.VK_PIPELINE_STAGE_2_COPY_BIT),
    RESOLVE(VK13.VK_PIPELINE_STAGE_2_RESOLVE_BIT),
    BLIT(VK13.VK_PIPELINE_STAGE_2_BLIT_BIT),
    CLEAR(VK13.VK_PIPELINE_STAGE_2_CLEAR_BIT),
    INDEX_INPUT(VK13.VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT),
    VERTEX_ATTRIBUTE_INPUT(VK13.VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT),
    PRE_RASTERIZATION_SHADERS(VK13.VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT),

    VIDEO_DECODE_KHR(KHRVideoDecodeQueue.VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR),
    VIDEO_ENCODE_KHR(KHRVideoEncodeQueue.VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR),

    TRANSFORM_FEEDBACK_EXT(KHRSynchronization2.VK_PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT),
    CONDITIONAL_RENDERING_EXT(KHRSynchronization2.VK_PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT),
    COMMAND_PREPROCESS_NV(KHRSynchronization2.VK_PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_NV),
    FRAGMENT_SHADING_RATE_ATTACHMENT_KHR(KHRSynchronization2.VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR),
    ACCELERATION_STRUCTURE_BUILD_KHR(KHRSynchronization2.VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR),
    RAY_TRACING_SHADER_KHR(KHRSynchronization2.VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR),
    FRAGMENT_DENSITY_PROCESS_EXT(KHRSynchronization2.VK_PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT),
    TASK_SHADER_EXT(KHRSynchronization2.VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT),
    MESH_SHADER_EXT(KHRSynchronization2.VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT),

    SUBPASS_SHADER_HUAWEI(HUAWEISubpassShading.VK_PIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEI),

    INVOCATION_MASK_HUAWEI(HUAWEIInvocationMask.VK_PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI),

    ACCELERATION_STRUCTURE_COPY_KHR(KHRRayTracingMaintenance1.VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR),

    MICROMAP_BUILD_EXT(EXTOpacityMicromap.VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT),

    CLUSTER_CULLING_SHADER_HUAWEI(HUAWEIClusterCullingShader.VK_PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI),

    OPTICAL_FLOW_NV(NVOpticalFlow.VK_PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV),

    CONVERT_COOPERATIVE_VECTOR_MATRIX_NV(NVCooperativeVector.VK_PIPELINE_STAGE_2_CONVERT_COOPERATIVE_VECTOR_MATRIX_BIT_NV),

    DATA_GRAPH_ARM(ARMDataGraph.VK_PIPELINE_STAGE_2_DATA_GRAPH_BIT_ARM),

    COPY_INDIRECT_KHR(KHRCopyMemoryIndirect.VK_PIPELINE_STAGE_2_COPY_INDIRECT_BIT_KHR),

    MEMORY_DECOMPRESSION_EXT(EXTMemoryDecompression.VK_PIPELINE_STAGE_2_MEMORY_DECOMPRESSION_BIT_EXT)


    ;

    private final long flag;
    VulkanicPipelineStageFlag(long flag) {
        this.flag = flag;
    }

    @Override
    public Long flag() {
        return flag;
    }
}
