package net.flamgop.vulkanic.memory;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicBufferUsageFlag implements Bitmaskable<Integer> {
    TRANSFER_SRC(VK10.VK_BUFFER_USAGE_TRANSFER_SRC_BIT),
    TRANSFER_DST(VK10.VK_BUFFER_USAGE_TRANSFER_DST_BIT),
    UNIFORM_TEXEL_BUFFER(VK10.VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT),
    STORAGE_TEXEL_BUFFER(VK10.VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT),
    UNIFORM_BUFFER(VK10.VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT),
    STORAGE_BUFFER(VK10.VK_BUFFER_USAGE_STORAGE_BUFFER_BIT),
    INDEX_BUFFER(VK10.VK_BUFFER_USAGE_INDEX_BUFFER_BIT),
    VERTEX_BUFFER(VK10.VK_BUFFER_USAGE_VERTEX_BUFFER_BIT),
    INDIRECT_BUFFER(VK10.VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT),

    SHADER_DEVICE_ADDRESS(VK12.VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT),

    VIDEO_DECODE_SRC_KHR(KHRVideoDecodeQueue.VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR),
    VIDEO_DECODE_DST_KHR(KHRVideoDecodeQueue.VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR),

    TRANSFORM_FEEDBACK_BUFFER_EXT(EXTTransformFeedback.VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT),
    TRANSFORM_FEEDBACK_COUNTER_BUFFER_EXT(EXTTransformFeedback.VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT),

    CONDITIONAL_RENDERING_EXT(EXTConditionalRendering.VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT),

    EXECUTION_GRAPH_SCRATCH_AMDX(AMDXShaderEnqueue.VK_BUFFER_USAGE_EXECUTION_GRAPH_SCRATCH_BIT_AMDX),

    DESCRIPTOR_HEAP_EXT(EXTDescriptorHeap.VK_BUFFER_USAGE_DESCRIPTOR_HEAP_BIT_EXT),

    ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_KHR(KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR),
    ACCELERATION_STRUCTURE_STORAGE_KHR(KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR),

    SHADER_BINDING_TABLE_KHR(KHRRayTracingPipeline.VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR),

    VIDEO_ENCODE_DST_KHR(KHRVideoEncodeQueue.VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR),
    VIDEO_ENCODE_SRC_KHR(KHRVideoEncodeQueue.VK_BUFFER_USAGE_VIDEO_ENCODE_SRC_BIT_KHR),

    SAMPLER_DESCRIPTOR_BUFFER_EXT(EXTDescriptorBuffer.VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT),
    RESOURCE_DESCRIPTOR_BUFFER_EXT(EXTDescriptorBuffer.VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT),
    PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_EXT(EXTDescriptorBuffer.VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT),

    MICROMAP_BUILD_INPUT_READ_ONLY_EXT(EXTOpacityMicromap.VK_BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT),
    MICROMAP_STORAGE_EXT(EXTOpacityMicromap.VK_BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT),

    TILE_MEMORY_QCOM(QCOMTileMemoryHeap.VK_BUFFER_USAGE_TILE_MEMORY_BIT_QCOM),

    RAY_TRACING_NV(NVRayTracing.VK_BUFFER_USAGE_RAY_TRACING_BIT_NV),
    ;

    private final int flag;
    VulkanicBufferUsageFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
