package net.flamgop.vulkanic.pipeline.descriptor.heap;

import org.lwjgl.vulkan.EXTDescriptorHeap;

public enum VulkanicDescriptorMappingSource {
    HEAP_WITH_CONSTANT_OFFSET(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_CONSTANT_OFFSET_EXT),
    HEAP_WITH_PUSH_INDEX(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_PUSH_INDEX_EXT),
    HEAP_WITH_INDIRECT_INDEX(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_INDIRECT_INDEX_EXT),
    HEAP_WITH_INDIRECT_INDEX_ARRAY(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_INDIRECT_INDEX_ARRAY_EXT),
    RESOURCE_HEAP_DATA(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_RESOURCE_HEAP_DATA_EXT),
    PUSH_DATA(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_PUSH_DATA_EXT),
    PUSH_ADDRESS(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_PUSH_ADDRESS_EXT),
    INDIRECT_ADDRESS(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_INDIRECT_ADDRESS_EXT),

    HEAP_WITH_SHADER_RECORD_INDEX(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_SHADER_RECORD_INDEX_EXT), // VK_KHR_ray_tracing_pipeline
    SHADER_RECORD_DATA(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_SHADER_RECORD_DATA_EXT), // VK_KHR_ray_tracing_pipeline
    SHADER_RECORD_ADDRESS(EXTDescriptorHeap.VK_DESCRIPTOR_MAPPING_SOURCE_SHADER_RECORD_ADDRESS_EXT), // VK_KHR_ray_tracing_pipeline
    ;
    private final int qualifier;

    VulkanicDescriptorMappingSource(int qualifier) {
        this.qualifier = qualifier;
    }

    public int qualifier() { return this.qualifier; }
}
