package net.flamgop.vulkanic.command;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.*;

public enum VulkanicAccessFlag implements Bitmaskable<Long> {
    NONE(VK13.VK_ACCESS_2_NONE),
    INDIRECT_COMMAND_READ(VK13.VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT),
    INDEX_READ(VK13.VK_ACCESS_2_INDEX_READ_BIT),
    VERTEX_ATTRIBUTE_READ(VK13.VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT),
    UNIFORM_READ(VK13.VK_ACCESS_2_UNIFORM_READ_BIT),
    INPUT_ATTACHMENT_READ(VK13.VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT),
    SHADER_READ(VK13.VK_ACCESS_2_SHADER_READ_BIT),
    SHADER_WRITE(VK13.VK_ACCESS_2_SHADER_WRITE_BIT),
    COLOR_ATTACHMENT_READ(VK13.VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT),
    COLOR_ATTACHMENT_WRITE(VK13.VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT),
    DEPTH_STENCIL_ATTACHMENT_READ(VK13.VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT),
    DEPTH_STENCIL_ATTACHMENT_WRITE(VK13.VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT),
    TRANSFER_READ(VK13.VK_ACCESS_2_TRANSFER_READ_BIT),
    TRANSFER_WRITE(VK13.VK_ACCESS_2_TRANSFER_WRITE_BIT),
    HOST_READ(VK13.VK_ACCESS_2_HOST_READ_BIT),
    HOST_WRITE(VK13.VK_ACCESS_2_HOST_WRITE_BIT),
    MEMORY_READ(VK13.VK_ACCESS_2_MEMORY_READ_BIT),
    MEMORY_WRITE(VK13.VK_ACCESS_2_MEMORY_WRITE_BIT),
    SHADER_SAMPLED_READ(VK13.VK_ACCESS_2_SHADER_SAMPLED_READ_BIT),
    SHADER_STORAGE_READ(VK13.VK_ACCESS_2_SHADER_STORAGE_READ_BIT),
    SHADER_STORAGE_WRITE(VK13.VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT),

    VIDEO_DECODE_READ_KHR(KHRVideoDecodeQueue.VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR),
    VIDEO_DECODE_WRITE_KHR(KHRVideoDecodeQueue.VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR),

    SAMPLER_HEAP_READ_EXT(EXTDescriptorHeap.VK_ACCESS_2_SAMPLER_HEAP_READ_BIT_EXT),
    RESOURCE_HEAP_READ_EXT(EXTDescriptorHeap.VK_ACCESS_2_RESOURCE_HEAP_READ_BIT_EXT),

    VIDEO_ENCODE_READ_KHR(KHRVideoEncodeQueue.VK_ACCESS_2_VIDEO_ENCODE_READ_BIT_KHR),
    VIDEO_ENCODE_WRITE_KHR(KHRVideoEncodeQueue.VK_ACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHR),

    SHADER_TILE_ATTACHMENT_READ_QCOM(QCOMTileShading.VK_ACCESS_2_SHADER_TILE_ATTACHMENT_READ_BIT_QCOM),
    SHADER_TILE_ATTACHMENT_WRITE_QCOM(QCOMTileShading.VK_ACCESS_2_SHADER_TILE_ATTACHMENT_WRITE_BIT_QCOM),

    TRANSFORM_FEEDBACK_WRITE_EXT(KHRSynchronization2.VK_ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT),
    TRANSFORM_FEEDBACK_COUNTER_READ_EXT(KHRSynchronization2.VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT),
    TRANSFORM_FEEDBACK_COUNTER_WRITE_EXT(KHRSynchronization2.VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT),
    CONDITIONAL_RENDERING_READ_EXT(KHRSynchronization2.VK_ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT),
    COMMAND_PREPROCESS_READ_EXT(KHRSynchronization2.VK_ACCESS_2_COMMAND_PREPROCESS_READ_BIT_EXT),
    COMMAND_PREPROCESS_WRITE_EXT(KHRSynchronization2.VK_ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_EXT),
    FRAGMENT_SHADING_RATE_ATTACHMENT_READ_KHR(KHRSynchronization2.VK_ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR),
    SHADING_RATE_IMAGE_READ_NV(KHRSynchronization2.VK_ACCESS_2_SHADING_RATE_IMAGE_READ_BIT_NV),
    ACCELERATION_STRUCTURE_READ_KHR(KHRSynchronization2.VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR),
    ACCELERATION_STRUCTURE_WRITE_KHR(KHRSynchronization2.VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR),
    FRAGMENT_DENSITY_MAP_READ_EXT(KHRSynchronization2.VK_ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT),
    COLOR_ATTACHMENT_READ_NONCOHERENT_EXT(KHRSynchronization2.VK_ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT),

    DESCRIPTOR_BUFFER_READ_EXT(EXTDescriptorBuffer.VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT),

    INVOCATION_MASK_READ_HUAWEI(HUAWEIInvocationMask.VK_ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI),

    SHADER_BINDING_TABLE_READ_KHR(KHRRayTracingMaintenance1.VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR),

    MICROMAP_READ_EXT(EXTOpacityMicromap.VK_ACCESS_2_MICROMAP_READ_BIT_EXT),
    MICROMAP_WRITE_EXT(EXTOpacityMicromap.VK_ACCESS_2_MICROMAP_WRITE_BIT_EXT),

    OPTICAL_FLOW_READ_NV(NVOpticalFlow.VK_ACCESS_2_OPTICAL_FLOW_READ_BIT_NV),
    OPTICAL_FLOW_WRITE_NV(NVOpticalFlow.VK_ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV),

    DATA_GRAPH_READ_ARM(ARMDataGraph.VK_ACCESS_2_DATA_GRAPH_READ_BIT_ARM),
    DATA_GRAPH_WRITE_ARM(ARMDataGraph.VK_ACCESS_2_DATA_GRAPH_WRITE_BIT_ARM),

    MEMORY_DECOMPRESSION_READ_EXT(EXTMemoryDecompression.VK_ACCESS_2_MEMORY_DECOMPRESSION_READ_BIT_EXT),
    MEMORY_DECOMPRESSION_WRITE_EXT(EXTMemoryDecompression.VK_ACCESS_2_MEMORY_DECOMPRESSION_WRITE_BIT_EXT)

    ;

    private final long flag;
    VulkanicAccessFlag(long flag) {
        this.flag = flag;
    }

    @Override
    public Long flag() {
        return flag;
    }
}
