package net.flamgop.vulkanic.core;

import org.jetbrains.annotations.NotNull;
import org.lwjgl.vulkan.*;

import java.util.HashMap;
import java.util.Map;

public enum VulkanicObjectType {
    UNKNOWN(VK10.VK_OBJECT_TYPE_UNKNOWN),
    INSTANCE(VK10.VK_OBJECT_TYPE_INSTANCE),
    PHYSICAL_DEVICE(VK10.VK_OBJECT_TYPE_PHYSICAL_DEVICE),
    DEVICE(VK10.VK_OBJECT_TYPE_DEVICE),
    QUEUE(VK10.VK_OBJECT_TYPE_QUEUE),
    SEMAPHORE(VK10.VK_OBJECT_TYPE_SEMAPHORE),
    COMMAND_BUFFER(VK10.VK_OBJECT_TYPE_COMMAND_BUFFER),
    FENCE(VK10.VK_OBJECT_TYPE_FENCE),
    DEVICE_MEMORY(VK10.VK_OBJECT_TYPE_DEVICE_MEMORY),
    BUFFER(VK10.VK_OBJECT_TYPE_BUFFER),
    IMAGE(VK10.VK_OBJECT_TYPE_IMAGE),
    EVENT(VK10.VK_OBJECT_TYPE_EVENT),
    QUERY_POOL(VK10.VK_OBJECT_TYPE_QUERY_POOL),
    BUFFER_VIEW(VK10.VK_OBJECT_TYPE_BUFFER_VIEW),
    IMAGE_VIEW(VK10.VK_OBJECT_TYPE_IMAGE_VIEW),
    SHADER_MODULE(VK10.VK_OBJECT_TYPE_SHADER_MODULE),
    PIPELINE_CACHE(VK10.VK_OBJECT_TYPE_PIPELINE_CACHE),
    PIPELINE_LAYOUT(VK10.VK_OBJECT_TYPE_PIPELINE_LAYOUT),
    RENDER_PASS(VK10.VK_OBJECT_TYPE_RENDER_PASS),
    PIPELINE(VK10.VK_OBJECT_TYPE_PIPELINE),
    DESCRIPTOR_SET_LAYOUT(VK10.VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT),
    SAMPLER(VK10.VK_OBJECT_TYPE_SAMPLER),
    DESCRIPTOR_POOL(VK10.VK_OBJECT_TYPE_DESCRIPTOR_POOL),
    DESCRIPTOR_SET(VK10.VK_OBJECT_TYPE_DESCRIPTOR_SET),
    FRAMEBUFFER(VK10.VK_OBJECT_TYPE_FRAMEBUFFER),
    COMMAND_POOL(VK10.VK_OBJECT_TYPE_COMMAND_POOL),

    DESCRIPTOR_UPDATE_TEMPLATE(VK11.VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE),
    SAMPLER_YCBCR_CONVERSION(VK11.VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION),

    PRIVATE_DATA_SLOT(VK13.VK_OBJECT_TYPE_PRIVATE_DATA_SLOT),

    SURFACE_KHR(KHRSurface.VK_OBJECT_TYPE_SURFACE_KHR),

    SWAPCHAIN_KHR(KHRSwapchain.VK_OBJECT_TYPE_SWAPCHAIN_KHR),

    DISPLAY_KHR(KHRDisplay.VK_OBJECT_TYPE_DISPLAY_KHR),
    DISPLAY_MODE_KHR(KHRDisplay.VK_OBJECT_TYPE_DISPLAY_MODE_KHR),

    DEBUG_REPORT_CALLBACK_EXT(EXTDebugReport.VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT),

    VIDEO_SESSION_KHR(KHRVideoQueue.VK_OBJECT_TYPE_VIDEO_SESSION_KHR),
    VIDEO_SESSION_PARAMETERS_KHR(KHRVideoQueue.VK_OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR),

    CU_MODULE_NVX(NVXBinaryImport.VK_OBJECT_TYPE_CU_MODULE_NVX),
    CU_FUNCTION_NVX(NVXBinaryImport.VK_OBJECT_TYPE_CU_FUNCTION_NVX),

    DEBUG_UTILS_MESSENGER_EXT(EXTDebugUtils.VK_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT),

    ACCELERATION_STRUCTURE_KHR(KHRAccelerationStructure.VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR),

    VALIDATION_CACHE_EXT(EXTValidationCache.VK_OBJECT_TYPE_VALIDATION_CACHE_EXT),

    ACCELERATION_STRUCTURE_NV(NVRayTracing.VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV),

    PERFORMANCE_CONFIGURATION_INTEL(INTELPerformanceQuery.VK_OBJECT_TYPE_PERFORMANCE_CONFIGURATION_INTEL),

    DEFERRED_OPERATION_KHR(KHRDeferredHostOperations.VK_OBJECT_TYPE_DEFERRED_OPERATION_KHR),

    INDIRECT_COMMANDS_LAYOUT_NV(NVDeviceGeneratedCommands.VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NV),

    CUDA_MODULE_NV(NVCudaKernelLaunch.VK_OBJECT_TYPE_CUDA_MODULE_NV),
    CUDA_FUNCTION_NV(NVCudaKernelLaunch.VK_OBJECT_TYPE_CUDA_FUNCTION_NV),

//    BUFFER_COLLECTION_FUCHSIA(FUCHSIABufferCollection.VK_OBJECT_TYPE_BUFFER_COLLECTION_FUCHSIA), // ???

    MICROMAP_EXT(EXTOpacityMicromap.VK_OBJECT_TYPE_MICROMAP_EXT),

    TENSOR_ARM(ARMTensors.VK_OBJECT_TYPE_TENSOR_ARM),
    TENSOR_VIEW_ARM(ARMTensors.VK_OBJECT_TYPE_TENSOR_VIEW_ARM),

    OPTICAL_FLOW_SESSION_NV(NVOpticalFlow.VK_OBJECT_TYPE_OPTICAL_FLOW_SESSION_NV),

    SHADER_EXT(EXTShaderObject.VK_OBJECT_TYPE_SHADER_EXT),

    PIPELINE_BINARY_KHR(KHRPipelineBinary.VK_OBJECT_TYPE_PIPELINE_BINARY_KHR),

    DATA_GRAPH_PIPELINE_SESSION_ARM(ARMDataGraph.VK_OBJECT_TYPE_DATA_GRAPH_PIPELINE_SESSION_ARM),

    EXTERNAL_COMPUTE_QUEUE_NV(NVExternalComputeQueue.VK_OBJECT_TYPE_EXTERNAL_COMPUTE_QUEUE_NV),

    INDIRECT_COMMANDS_LAYOUT_EXT(EXTDeviceGeneratedCommands.VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_EXT),
    INDIRECT_EXECUTION_SET_EXT(EXTDeviceGeneratedCommands.VK_OBJECT_TYPE_INDIRECT_EXECUTION_SET_EXT),

//    SHADER_INSTRUMENTATION_ARM(ARMShaderInstrumentation.VK_OBJECT_TYPE_SHADER_INSTRUMENTATION_ARM), // ??

    ;
    private static final Map<Integer, VulkanicObjectType> LOOKUP = new HashMap<>();
    static {
        for (VulkanicObjectType type : values()) {
            LOOKUP.put(type.qualifier, type);
        }
    }

    private final int qualifier;
    VulkanicObjectType(int qualifier) {
        this.qualifier = qualifier;
    }

    public int qualifier() {
        return qualifier;
    }

    public static @NotNull VulkanicObjectType valueOf(int value) {
        return LOOKUP.getOrDefault(value, UNKNOWN);
    }
}
