package net.flamgop.vulkanic.memory;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.util.vma.Vma;

public enum VulkanicAllocationCreateFlag implements Bitmaskable<Integer> {
    DEDICATED_MEMORY(Vma.VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT),
    NEVER_ALLOCATE(Vma.VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT),
    MAPPED(Vma.VMA_ALLOCATION_CREATE_MAPPED_BIT),
    USER_DATA_COPY_STRING(Vma.VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT),
    UPPER_ADDRESS(Vma.VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT),
    DONT_BIND(Vma.VMA_ALLOCATION_CREATE_DONT_BIND_BIT),
    WITHIN_BUDGET(Vma.VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT),
    CAN_ALIAS(Vma.VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT),
    HOST_ACCESS_SEQUENTIAL_WRITE(Vma.VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT),
    HOST_ACCESS_RANDOM(Vma.VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT),
    HOST_ACCESS_ALLOW_TRANSFER_INSTEAD(Vma.VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT),
    STRATEGY_MIN_MEMORY(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT),
    STRATEGY_MIN_TIME(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT),
    STRATEGY_MIN_OFFSET(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT),
    STRATEGY_BEST_FIT(Vma.VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT),
    STRATEGY_FIRST_FIT(Vma.VMA_VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT),
    STRATEGY_MASK(Vma.VMA_ALLOCATION_CREATE_STRATEGY_MASK),

    ;
    private final int flag;
    VulkanicAllocationCreateFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
