package net.flamgop.vulkanic.sync;

import net.flamgop.vulkanic.util.Bitmaskable;
import org.lwjgl.vulkan.EXTMeshShader;
import org.lwjgl.vulkan.HUAWEIClusterCullingShader;
import org.lwjgl.vulkan.VK10;

public enum VulkanicQueryPipelineStatisticFlag implements Bitmaskable<Integer> {
    /// Specifies that queries managed by the pool will count the number of vertices processed by the input assembly stage.
    INPUT_ASSEMBLY_VERTICES(VK10.VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT),
    /// Specifies that queries managed by the pool will count the number of primitives processed by the input assembly stage
    INPUT_ASSEMBLY_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT),
    /// Specifies that queries managed by the pool will count the number of vertex shader invocations.
    VERTEX_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT),
    /// Specifies that queries managed by the pool will count the number of geometry shader invocations
    GEOMETRY_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT),
    /// Specifies that queries managed by the pool will count the number of primitives generated by geometry shader invocations
    GEOMETRY_SHADER_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT),
    /// Specifies that queries managed by the pool will count the number of primitives processed by the Primitive Clipping stage of the pipeline
    CLIPPING_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT),
    /// Specifies that queries managed by the pool will count the number of primitives output by the Primitive Clipping stage of the pipeline
    CLIPPING_PRIMITIVES(VK10.VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT),
    /// Specifies that queries managed by the pool will count the number of fragment shader invocations
    FRAGMENT_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT),
    /// Specifies that queries managed by the pool will count the number of patches processed by the tessellation control shader
    TESSELLATION_CONTROL_SHADER_PATCHES(VK10.VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT),
    /// Specifies that queries managed by the pool will count the number of invocations of the tessellation evaluation shader
    TESSELLATION_EVALUATION_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT),
    /// Specifies that queries managed by the pool will count the number of compute shader invocations
    COMPUTE_SHADER_INVOCATIONS(VK10.VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT),

    /// Specifies that queries managed by the pool will count the number of task shader invocations
    TASK_SHADER_INVOCATIONS_EXT(EXTMeshShader.VK_QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT),
    /// Specifies that queries managed by the pool will count the number of mesh shader invocations
    MESH_SHADER_INVOCATIONS_EXT(EXTMeshShader.VK_QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT),

    /// Specifies that queries managed by the pool will count the number of cluster culling shader invocations
    CLUSTER_CULLING_SHADER_INVOCATIONS_HUAWEI(HUAWEIClusterCullingShader.VK_QUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI),

    ;
    private final int flag;
    VulkanicQueryPipelineStatisticFlag(int flag) {
        this.flag = flag;
    }

    @Override
    public Integer flag() {
        return flag;
    }
}
