package net.flamgop.vulkanic.sync;

import org.lwjgl.vulkan.*;

public enum VulkanicQueryType {
    OCCLUSION(VK10.VK_QUERY_TYPE_OCCLUSION),
    PIPELINE_STATISTICS(VK10.VK_QUERY_TYPE_PIPELINE_STATISTICS),
    TIMESTAMP(VK10.VK_QUERY_TYPE_TIMESTAMP),

    RESULT_STATUS_ONLY_KHR(KHRVideoQueue.VK_QUERY_TYPE_RESULT_STATUS_ONLY_KHR),

    TRANSFORM_FEEDBACK_STREAM_EXT(EXTTransformFeedback.VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT),

    PERFORMANCE_QUERY_KHR(KHRPerformanceQuery.VK_QUERY_TYPE_PERFORMANCE_QUERY_KHR),

    ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR(KHRAccelerationStructure.VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR),
    ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR(KHRAccelerationStructure.VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR),

    PERFORMANCE_QUERY_INTEL(INTELPerformanceQuery.VK_QUERY_TYPE_PERFORMANCE_QUERY_INTEL),

    VIDEO_ENCODE_FEEDBACK_KHR(KHRVideoEncodeQueue.VK_QUERY_TYPE_VIDEO_ENCODE_FEEDBACK_KHR),

    MESH_PRIMITIVES_GENERATED_EXT(EXTPrimitivesGeneratedQuery.VK_QUERY_TYPE_PRIMITIVES_GENERATED_EXT),

    ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR(KHRRayTracingMaintenance1.VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR),
    ACCELERATION_STRUCTURE_SIZE_KHR(KHRRayTracingMaintenance1.VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHR),

    MICROMAP_SERIALIZATION_SIZE_EXT(EXTOpacityMicromap.VK_QUERY_TYPE_MICROMAP_SERIALIZATION_SIZE_EXT),
    MICROMAP_COMPACTED_SIZE_EXT(EXTOpacityMicromap.VK_QUERY_TYPE_MICROMAP_COMPACTED_SIZE_EXT),

    ;
    private final int qualifier;
    VulkanicQueryType(int qualifier) {
        this.qualifier = qualifier;
    }

    public int qualifier() {
        return qualifier;
    }
}
