package net.flamgop.vulkanic.pipeline.descriptor;

import org.lwjgl.vulkan.*;

public enum VulkanicDescriptorType {
    SAMPLER(VK10.VK_DESCRIPTOR_TYPE_SAMPLER),
    COMBINED_IMAGE_SAMPLER(VK10.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER),
    SAMPLED_IMAGE(VK10.VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
    STORAGE_IMAGE(VK10.VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
    UNIFORM_TEXEL_BUFFER(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER),
    STORAGE_TEXEL_BUFFER(VK10.VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER),
    UNIFORM_BUFFER(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER),
    STORAGE_BUFFER(VK10.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
    UNIFORM_BUFFER_DYNAMIC(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC),
    STORAGE_BUFFER_DYNAMIC(VK10.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC),
    INPUT_ATTACHMENT(VK10.VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT),

    INLINE_UNIFORM_BLOCK(VK13.VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK),

    ACCELERATION_STRUCTURE_KHR(KHRAccelerationStructure.VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR),

    ACCELERATION_STRUCTURE_NV(NVRayTracing.VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV),

    SAMPLE_WEIGHT_IMAGE_QCOM(QCOMImageProcessing.VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM),
    BLOCK_MATCH_IMAGE_QCOM(QCOMImageProcessing.VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM),

    TENSOR_ARM(ARMTensors.VK_DESCRIPTOR_TYPE_TENSOR_ARM),

    MUTABLE_EXT(EXTMutableDescriptorType.VK_DESCRIPTOR_TYPE_MUTABLE_EXT),

    PARTITIONED_ACCELERATION_STRUCTURE_NV(NVPartitionedAccelerationStructure.VK_DESCRIPTOR_TYPE_PARTITIONED_ACCELERATION_STRUCTURE_NV),

    INLINE_UNIFORM_BLOCK_EXT(EXTInlineUniformBlock.VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT),

    MUTABLE_VALVE(VALVEMutableDescriptorType.VK_DESCRIPTOR_TYPE_MUTABLE_VALVE),
    ;

    private final int qualifier;
    VulkanicDescriptorType(int qualifier) {
        this.qualifier = qualifier;
    }
    public int qualifier() {
        return qualifier;
    }
}
